import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My site", //website title
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <header>
          <img 
            src="/images/company-logo.png" 
            alt="Company Logo" 
            width="120" 
          />
          <h1>Royal Tour</h1>
          <p>"Your Belief, Our Faith"</p>
        </header>
        {children}
        <footer>
          <p>© 2025 Royal Tour Management System | Travel with Trust</p>
        </footer>
      </body>
    </html>
  );
}
